name: CI/CD with Maven and SSH

on:
  push:
    branches:
      - develop  

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install
        continue-on-error: true 
        id: mvn_build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh javaserver@103.31.250.187 'cd byrtagihan/server-byrtagihan && git pull origin develop && mvn clean install'
        continue-on-error: true  
