name: CI/CD with Maven

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 103.31.250.187
          username: javaserver
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Stop existing Java application (if applicable)
            # Example: systemctl stop your-app-service

            # Copy the built JAR file to the server
            # Example: scp target/your-app.jar javaserver@103.31.250.187:/path/to/destination/

            # Restart Java application (if applicable)
            # Example: systemctl start your-app-service
