name: CI/CD with Maven and SSH

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 103.31.250.187
          username: javaserver
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
          
            systemctl stop server-byrtagihan

         
            scp target/server-byrtagihan-0.0.1-SNAPSHOT.jar javaserver@103.31.250.187:server-byrtagihan/

           
            systemctl start server-byrtagihan
